language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

before_script:
  - printf "\n" | pecl install imagick
  - composer install --prefer-source

script:
  - ./bin/phpspec run -f pretty
  - ./bin/behat --format=progress